python2/httplib2/__init__.py, python2/httplib2/test/other_cacerts.txt, python2/httplib2test.py, python2/ssl_protocol_test.py
NEW: Support for specifying the SSL protocol version (Python v2).
This fixes #8. No ETA for Python v3 support.
=> NEW: Support for specifying the SSL protocol version (Python v2)

python2/httplib2/__init__.py
Commit 9e1c4e5e56 checks socket.getdefaulttimeout(), but uses 5 if it is not
set. Instead, pass None to urlfetch, so it will use its own built-in
default. This makes this respect urlfetch.set_default_fetch_deadline(), as
it did before.
We upgraded from an ancient version of httplib2 to the current version, and hit this change in behaviour between the two versions. This fixes it to act like the previous.
=> CHANGE: On App Engine use urlfetch's default deadline if None is passed.

python2/httplib2/__init__.py, python2/httplib2test_appengine.py
* Fix TypeError exception “__init__() got an unexpected keyword argument 'ssl_version’”
* Add additional Google App Engine environment checks
* Remove broken App Engine test cases
=> FIX: TypeError exception when running on Google App Engine.

python2/httplib2/__init__.py, python2/httplib2/test/miniserver.py, python2/httplib2/test/server.key, python2/httplib2/test/server.pem, python2/httplib2/test/test_ssl_context.py
Make use of the backported `ssl.SSLContext` that is available since Python 2.7.9 to send the hostname as part of the SSL connection to the server.
=> Send SNI data for SSL connections on Python 2.7.9+

python3/httplib2/__init__.py
fix the disable_ssl_certificate_validation option with python 3.5 - based on https://github.com/jcgregorio/httplib2/pull/289
=> FIX: Make disable_ssl_certificate_validation work with Python 3.5.

python2/httplib2/__init__.py, python2/httplib2/socks.py, python2/httplib2test.py, python3/httplib2/__init__.py, python3/httplib2test.py
This argument lets the user add to or override the headers in the
HTTP CONNECT request sent to the proxy.  Some proxy servers need
additional arguments that are not provided by default by httplib2.
Note that although this commit makes this enhancement for both the
python2 and python3 versions of this library, the python3 version
does not implement ProxyInfo at all (and never has).
Signed-off-by: Martin Carroll <martin.carroll@nokia-bell-labs.com>
=> Add new proxy_headers argument to ProxyInfo constructor.

python2/httplib2/__init__.py
This was originally done for issues with making this work with an internal version of dev_appserver which is no longer needed. Hence, removing these references
=> Remove references to google3 from httplib2

doc/html/_sources/libhttplib2.txt
I have noticed some minors typos problems when working on the instant answer for httplib2 for duckduckgo ( https://github.com/duckduckgo/zeroclickinfo-fathead/pull/458 ), so I just corrected them if you want to use them.
I also noticed that the readthedocs page links to the old repository but I do not know how to change it.
=> Minor typos changes in the documentation

python2/httplib2/__init__.py, python3/httplib2/__init__.py
Refer to https://stackoverflow.com/a/22311297
zlib library supports:
RFC 1950 (zlib compressed format)
RFC 1951 (deflate compressed format)
RFC 1952 (gzip compressed format)
choosing windowBits
to (de-)compress deflate format, use wbits = -zlib.MAX_WBITS
to (de-)compress zlib format, use wbits = zlib.MAX_WBITS
to (de-)compress gzip format, use wbits = zlib.MAX_WBITS | 16
See documentation in http://www.zlib.net/manual.html#Advanced (section inflateInit2)
Signed-off-by: Phus Lu <phuslu@hotmail.com>
=> Bugfix for Content-Encoding: deflate

python2/httplib2/socks.py
In python 2, use socks5 proxy, 
```
File "/Users/kebeliu/workspace/daocloud/dcv_customer_rate/venv/lib/python2.7/site-packages/httplib2/__init__.py", line 1659, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "/Users/kebeliu/workspace/daocloud/dcv_customer_rate/venv/lib/python2.7/site-packages/httplib2/__init__.py", line 1399, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "/Users/kebeliu/workspace/daocloud/dcv_customer_rate/venv/lib/python2.7/site-packages/httplib2/__init__.py", line 1319, in _conn_request
conn.connect()
File "/Users/kebeliu/workspace/daocloud/dcv_customer_rate/venv/lib/python2.7/site-packages/httplib2/__init__.py", line 1065, in …
```
=> > fix UnicodeDecodeError using socks5 proxy.

python2/httplib2/__init__.py
When a user has both IPv4 and IPv6 enabled, `socket.getaddrinfo` returns 2 entries. The entry for IPv6 has family = 10, while the IPv4 entry has family = 2. In `HTTPSConnectionWithTimeout`, if a socket is created with family = 10 at line 1063, but the host name is resolved as an IPv4 address in line 1068, `sock.connect` times out.
I changed `HTTPConnectionWithTimeout` as well since the code is similar.
It worth mentioning that this issue does not always happen when both IPv4 and IPv6 are enabled. On some machines, it fails consistently but on others it never times out. It may depend on how `socket.connect` resolves host names.
https://github.com/httplib2/httplib2/issues/56 looks like the same case.
Fixes #56.
=> FIX: A timeout issue when both IPv4 and IPv6 are enabled.

setup.py
It would also be good to explicitly report supported minor versions too. For example:
```
Programming Language :: Python :: 2
Programming Language :: Python :: 2.7
Programming Language :: Python :: 3.4
Programming Language :: Python :: 3.5
Programming Language :: Python :: 3.6
```
https://pypi.python.org/pypi?%3Aaction=list_classifiers
What minor versions does httplib2 currently support? I can't find it documented anywhere.
=> Classifiers: Python 2 is also supported

python2/httplib2/__init__.py, python2/httplib2/test/functional/test_proxies.py, python2/httplib2/test/test_ssl_context.py, python2/httplib2test.py, python3/httplib2/__init__.py
Changes that are compatible with both Python 2 and Python 3:
* dict.has_key(key) --> key in dict
* old style exceptions --> new style exceptions
* print() function
Make the minimal, safe changes required to convert the repo's code to be syntax compatible with both Python 2 and Python 3.
Run: [futurize --stage1 -w **/*.py](http://python-future.org/futurize_cheatsheet.html)
See Stage 1: "safe" fixes http://python-future.org/automatic_conversion.html#stage-1-safe-fixes
=> dict.has_key(key) --> key in dict, new style exceptions

python3/httplib2/__init__.py
This is adapapted from #73
#73 introduced a lot of white-space changes and automated clean-ups which made the patch hard to review.
It also copy-pasted (!) a socks.py module from SocksiPy.
This version does not ship a socks module, users that require a proxy will need to install their own socks library (I used PySocks) in addition to httplib2.
Since the default value for `proxy_info` is `proxy_info_from_environment`, this means that without any other changes, upgrading to this version will cause httplib2 to respect `HTTP_PROXY` / `HTTPS_PROXY` environment variables.
Closes #53 
Closes #25 
Closes #22
=> Cleaned-up python 3 proxy support

python3/httplib2/__init__.py, python3/httplib2/socks.py, tests/test_proxy.py
https://github.com/httplib2/httplib2/issues/11
@cveilleux please have a look at this. I know you wanted other destiny for socksipy, but hear my reasons for extending this copypaste vendoring to py3:
- less py2/3 differences
- py3 still prefers external package
- we'll make it right on merging py2/3 code
=> proxy: python3 support no_proxy and vendor socksipy

python2/httplib2/__init__.py, python3/httplib2/__init__.py, tests/test_other.py
This workaround is not needed anymore, right?
Origin: https://code.google.com/archive/p/httplib2/issues/17
> Year: 2008
> a bug on the Google servers end
> Location: header ... redirected to http://www.google.com:443 (instead of https)
Issue: https://github.com/httplib2/httplib2/issues/112 year 2018
Workaround in httplib2 does not allow weird but legitimate request.
`Http().request(..., connection_type=httplib2.HTTPConnectionWithTimeout)` fails on excess TLS-related arguments.
Arguably, this discovered problem that connection classes should have compatible constructor signatures, e.g. `Connection(uri, options)`
=> Revert http:443->https workaround

python3/httplib2/socks.py, tests/test_proxy.py
In `__getauthheader` auth object is a str. base64.b64encode(auth) expects a byte array, not a str, so it throws an error. Then base64.b64encode(auth) returns a bytes object, which can not be joined with `"Proxy-Authorization: Basic"`
=> Python3 HTTP-proxy b64encode TypeError: bytes-like object is required

setup.py
```
Warning: 'classifiers' should be a list, got type 'tuple'
```
Related issue: https://bugs.python.org/issue19610
=> Fix a warning under Python 3.7

.travis.yml, CHANGELOG, python2/httplib2/__init__.py, python3/httplib2/__init__.py, script/release, setup.cfg, setup.py
- py3 wheel in CI auto release
- whichever default python you have (also likely py3) for manual (interactive) run of script/release
Appended on top of irrelevant travis and cosmetic indent changes, which may not be accepted.
=>  release non-universal wheels

Makefile, python3/httplib2/__init__.py
The Python2 version of `HTTP.request` calls `self._get_proxy_info`, which calls `proxy_info.applies_to`
=> Python3: Use no_proxy

python2/httplib2/__init__.py, tests/test_other.py
This autoformatting PR actually changed the behavior of the error handling:
https://github.com/httplib2/httplib2/pull/105/files#diff-c6669c781a2dee1b2d2671cab4e21c66L985
"raise socket.err, msg" is not the same as "raise socket.error(msg)" in the case where msg is an exception. For instance consider:
msg = socket.timeout("foo")
raise socket.error, msg  # => socket.timeout: foo
raise socket.error(msg)  # => socket.error: foo
This has the effect of potentially changing the type of the error raised by connect(). Interestingly the PY3 copy of the code doesn't have this problem (probably cause it doesn't have msg at all; not sure if it's actually needed but I figured might as well keep it for PY2 in case it is).
The change I propose here will restore the original behavior prior to the …
=> Fix PY2 regression in connect() error handling.

python3/httplib2/__init__.py
There was one more layer of parentheses than there should have been.
Fixes #161.
=> Fix debug in HTTPSConnectionWithTimeout.connect

python2/httplib2/__init__.py
When using IronPython 2.7, importing httplib2 can raise an ImportError. It seems like a bug in IronPython but switching iri2uri's import to a relative import solves the issue and will still work in other python implementations. 
I've put together a simplified example of the structure that can cause the import error in IronPython in [code_structure.zip](https://github.com/httplib2/httplib2/files/4487909/code_structure.zip). It seems that under certain circumstances, once a relative import has been executed, the following absolute import does not search the local directory.
=> Relative import iri2uri

MANIFEST.in
This makes the test suite available to Debian/Ubuntu/...
It enables distributions to validate the quality of the shipped package.
This new test suite should be used, instead of the deprecated `python3/httplib2test.py` (see: https://github.com/httplib2/httplib2/issues/166)
=> Ship new test suite in source dist

python2/httplib2/__init__.py, python2/httplib2/auth.py, python2/httplib2/error.py, python3/httplib2/__init__.py, python3/httplib2/auth.py, python3/httplib2/error.py, requirements.txt, script/release, script/test, setup.py, tests/__init__.py, tests/test_auth.py
Fixes CPU burn DoS by cubic complexity of whitespace matching in
WWW_AUTH_RELAXED (default) regexp.
=> parse auth headers using pyparsing instead of regexp

requirements-test.txt, tests/test_cacerts_from_env.py, tests/test_http.py, tests/test_other.py, tests/test_proxy.py
Since Python 3.3, mock is part of unittest in the standard library.
Provide compatibility for older versions, since httplib2 seems to still support Python2.
=> Use mock from the standard library

python3/httplib2/__init__.py, tests/test_https.py
Python 3.7+ define TLS versions as an enum in ssl.TLSVersion. Following principle of least surprise for developers reading up on core SSL library, allow the enum to be passed directly to httplib2 without crashing. Crash is due to getattr requiring that the attribute name be a string, which ssl.TLSVersion does not provide. Continue to accept strings for compatibility with existing code bases.
=> Accept TLS min/max version enums

.travis.yml, setup.py
Add to CI and declare support in Trove classifiers.
Also add `python_requires` to help pip.
---
Python 2.7 and 3.4-3.5 are all EOL, perhaps now's a good time to drop support for them?
https://endoflife.date/python
=> Add support for Python 3.8 and 3.9

python3/httplib2/auth.py, requirements.txt
For #207.
Applies the patch @temoto shared in https://github.com/httplib2/httplib2/issues/207#issuecomment-951833266 and adjusts `requirements.txt` to install a compatible version of `pyparsing` based on the Python version.
=> Use pp.common.downcaseTokens for pyparsing v3

tests/test_http.py
This would silently skip the test unconditionally, and is a failure in pytest 7.0.0rc1
=> Fix incorrect pytest.mark.skip usage

python2/httplib2/__init__.py, python3/httplib2/__init__.py, tests/test_proxy.py
Parsing proxy was breaking when proxy URL was set to ipv6 address. There
was also weird handling of proxy without a password. We should rely on
parsing those fields in urllib which is present in all supported
versions.
=> Fix parsing http_proxy environment.

tests/test_other.py
There is a small typo in tests/test_other.py.
Should read `referring` rather than `referrring`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, referrring -> referring

python3/httplib2/__init__.py
Like the PROTOCOL_SSLv23 deprecation, this can be changed to use PROTOCOL_TLS_CLIENT
In the docs, PROTOCOL_TLS_CLIENT uses the same methods for client side as required in httplib2
Fixes #220
=> ssl: PROTOCOL_TLS is deprecated fix

python3/httplib2/__init__.py
Similar to https://github.com/httplib2/httplib2/pull/202 but the [socket.error](https://docs.python.org/3/library/socket.html) may also have empty args so check the length again, or revert to the `errno` field.
When I was using a proxy that dropped the connection I got this error message
```
socks.GeneralProxyError: Connection closed unexpectedly
During handling of the above exception, another exception occurred:
...
File "~/Applications/google-cloud-sdk/platform/gsutil/third_party/httplib2/python3/httplib2/__init__.py", line 195, in _errno_from_exception
return e_int.args[0].errno if isinstance(e_int.args[0], socket.error) else e_int.errno
IndexError: tuple index out of range
```
[httplib2_IndexError_tuple_index_out_of_range.txt](https://github.com/httplib2/httplib2/files/9456292/httplib2 …
=> Recursive _errno_from_exception

python3/httplib2/__init__.py, tests/test_https.py
I have encountered a problem with making HTTP requests when SSL cert validation is disabled. It is very easy to reproduce
```python
from httplib2 import Http, DEFAULT_TLS_VERSION
Http(disable_ssl_certificate_validation=True).request('https://github.com')
```
It turns out that if DEFAULT_TLS_VERSION is PROTOCOL_TLS_CLIENT then the following error will be thrown:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/tomasz.ziolkowski/venv/vclient-venv/lib/python3.8/site-packages/httplib2/__init__.py", line 1577, in request
conn = self.connections[conn_key] = connection_type(
File "/Users/tomasz.ziolkowski/venv/vclient-venv/lib/python3.8/site-packages/httplib2/__init__.py", line 1096, in __init__
context = _build_ssl_context(
File …
```
=> Fix disabling cert validation for PROTOCOL_TLS_CLIENT
